(function(){if(typeof document.getElementsByClassName=="undefined")document.getElementsByClassName=function(b){var d,c,a,f=[],g=document.getElementsByTagName?document.getElementsByTagName("*"):document.all;d=0;for(len=g.length;d<len;d++){a=g[d].className.split(/\s+/);for(c=0;c<a.length;c++)if(a[c]==b){f.push(g[d]);break}}return f};var r={create:function(){return function(){this.extend=function(b){var d=function(){this.initialize.apply(this,arguments)};for(var c in this)d.prototype[c]=this[c];for(c in b)d.prototype[c]=
b[c];return d};this.initialize.apply(this,arguments)}},register:function(b,d){b=b.split(".");for(var c=window,a=0,f=b.length;a<f;a++){if(typeof c[b[a]]=="undefined")c[b[a]]={};c=c[b[a]]}for(var g in d)c[g]=d[g]}},s=r.create();s.prototype={initialize:function(){this.scanner()},scanner:function(){for(var b=jp.atlantis.mashiron.advertise,d=document.getElementsByClassName("adlantiss_frame"),c=[],a=0,f=0;f<d.length;f++){for(var g,i="iframe",j=false,k=false,o=false,n=false,h=d[f].className.split(" "),e=
0;e<h.length;e++)switch(true){case h[e]=="loaded":k=true;break;case h[e]=="autosize":j=true;break;case h[e]=="nocss":n=true;break;case /^zid_.*$/.test(h[e]):g=/^zid_(.*)$/.exec(h[e])[1];break;case /^checksum_.*$/.test(h[e]):o=/^checksum_(.*)$/.exec(h[e])[1];break;case /^container_.*$/.test(h[e]):i=/^container_(.*)$/.exec(h[e])[1];break;case /^color_.*$/.test(h[e]):color=/^color_(.*)$/.exec(h[e])[1].split("-");break;default:}if(!(k||!g)){c.push(g);i={zid:g,checksum:o,id:a,containerTag:i,autosize:j,
nocss:n,classes:h};if(/iPhone OS.*Mobile\/5[A-H]/.test(navigator.userAgent))i.containerTag="div";if(typeof color!="undefined")i.color=color.length>1?{title:color[0],text:color[1],background:color[2],border:color[3],url:color[4]}:color[0];if(typeof AdLantisOptions!="undefined")for(e in AdLantisOptions)i[e]=typeof AdLantisOptions[e]=="function"?window.AdLantisOptions[e]():window.AdLantisOptions[e];e=document.getElementsByTagName("meta");j=0;for(k=e.length;j<k;j++){o=e[j];if(o.getAttribute("name")&&
o.getAttribute("name")=="adlantis-ad-params")i.adlantisAdParam=o.getAttribute("content")}e=new b(d[f],i);jp.atlantis.mashiron.ads["ads"+e.id]=e;a++;d[f].className+=" loaded"}}this.zidlist=c}};var t=r.create();t.prototype={domain:"http://ad.adlantis.jp/",rehearsal:false,requiredFlashVersion:"6",adlantisInfoURL:"http://www.adlantis.jp/?ref=ad_box",pathTextAdCSS:"http://static.adlantis.jp/stylesheets/multiple_text_ads.css",jsonendpoint:"ad/load_script",containerTag:"iframe",options:{forceHtmlAdInFrame:true,
forceNetworkAdInFrame:true},additionalParam:false,autosize:false,nocss:false,checksum:false,adlantisAdParam:false,initialize:function(){this.arguments=arguments;var b=this.arguments[0],d=this.arguments[1];for(var c in d)this[c]=d[c];if(this.checksum&&this.rehearsal){this.domain=this.rehearsal.domain;this.jsonendpoint=this.rehearsal.jsonendpoint}b.id=["adbox_",this.id].join("");this.containerElement=b;this.openJSONRequest(this.getURL());return this},openJSONRequest:function(b){putTag=function(){var c=
document.createElement("script");c.src=b;c.type="text/javascript";c.charset="UTF-8";document.body.appendChild(c)};if(window.opera){var d=document.createElement("img");d.onerror=putTag;d.width=0;d.height=0;d.src=b;document.body.appendChild(d)}else putTag.apply()},getURL:function(){var b=new Array(["zid",encodeURIComponent(this.zid)].join("="));b.push(["ref",document.referrer].join("="));b.push(["callbackid","ads"+this.id].join("="));this.checksum&&b.push(["checksum",this.checksum].join("="));this.adlantisAdParam&&
b.push(["adlantisAdParam",this.adlantisAdParam].join("="));if(this.additionalParam&&typeof this.additionalParam=="object")try{b.push(this.additionalParam.join("="))}catch(d){}return[this.domain,this.jsonendpoint,"?",b.join("&")].join("")},setVars:function(b){for(var d=0,c=this.containerElement.childNodes.length;d<c;d++)this.containerElement.removeChild(this.containerElement.childNodes[d]);if(typeof b.type!="undefined"){for(d in b)this[d]=b[d];if(this.type=="html"&&this.options.forceHtmlAdInFrame||
this.type=="externalNetwork"&&this.options.forceNetworkAdInFrame)this.containerTag="iframe";if(this.width=="auto"||this.height=="auto"){this.containerTag="div";this.autosize=true}this.subContainer=this.getContainer();this.insertElement(this.subContainer,this.containerElement);this.updateAdElement()}},getContainer:function(){var b=document.createElement(this.containerTag);if(this.containerTag=="iframe"){b.setAttribute("frameBorder","0");b.setAttribute("marginHeight","0");b.setAttribute("marginWidth",
"0");b.setAttribute("vspace","0");b.setAttribute("hspace","0");b.setAttribute("allowTransparency","true");b.setAttribute("scrolling","no")}if(this.width&&this.height&&!this.autosize){b.style.width=this.width+"px";b.style.height=this.height+"px"}return b},updateAdElement:function(){var b=function(h,e){var m=containerOrigin.createElement("a");m.href=h;m.target=e;return m},d=function(h,e,m){if(!this.nocss){for(var l=0,q=e.length;l<q;l++){var p=e[l];h.setAttribute(p[0],p[1]);if(p[0]=="class")h.className=
p[1]}l=0;for(q=m.length;l<q;l++){e=m[l];h.style[e[0]]=e[1]}}},c=function(h,e,m){h=containerOrigin.createElement(h);d(h,e,m);return h};if(this.containerTag=="iframe"){this.subContainer.setAttribute("frameBorder","0");var a=this.subContainer.contentDocument?this.subContainer.contentDocument:this.subContainer.contentWindow.document;if(this.type!="externalNetwork"&&this.type!="html"){a.writeln("<head></head><body></body>");a.close();containerOrigin=a;targetContainer=a.body;targetContainer.style.margin=
0;targetContainer.style.padding=0;targetContainer.style.backgroundColor="transparent"}}else{containerOrigin=document;targetContainer=this.subContainer}switch(this.type){case "externalNetwork":if(this.containerTag!="iframe")return false;this.subContainer.src=this.iframeLocation+"&magic="+Math.floor(Math.random()*3656158444729381).toString(36);break;case "text":var f=containerOrigin.createElement("div");f.style.textAlign=this.align;f.innerHTML=this.showPR?"[PR]"+decodeURIComponent(this.string):decodeURIComponent(this.string);
a=b(this.href,this.target);a.style.color=this.color;a.style.fontSize="13px";a.appendChild(f);targetContainer.appendChild(a);break;case "multiple":this.useList=false;var g=0;for(a=this.classes.length;g<a;g++)if(this.classes[g]=="use_list")this.useList=true;f=this.useList?containerOrigin.createElement("ul"):containerOrigin.createElement("div");g=0;for(a=this.ads.length;g<a;g++){ad=this.ads[g];var i=this.useList?containerOrigin.createElement("li"):containerOrigin.createElement("div");i.setAttribute("class",
"eachAd");var j;j=ad.showPR?containerOrigin.createTextNode("[PR]"+decodeURIComponent(ad.string)):containerOrigin.createTextNode(decodeURIComponent(ad.string));var k=b(ad.href,ad.target);k.appendChild(j);i.appendChild(k);f.appendChild(i)}targetContainer.appendChild(f);break;case "img":a=b(this.href,this.target);f=c("img",[["src",this.src],["alt",decodeURIComponent(this.alt)],["border","0"]],[["width",this.width+"px"],["height",this.height+"px"]]);a.appendChild(f);targetContainer.appendChild(a);break;
case "html":if(this.containerTag=="iframe"||this.options.forceHtmlAdInFrame)this.subContainer.src=this.iframeLocation+"&magic="+Math.floor(Math.random()*3656158444729381).toString(36);else targetContainer.innerHTML=decodeURIComponent(this.innerHTML);break;case "swf":try{f=(g=deconcept.SWFObjectUtil.getPlayerVersion())&&g.major>=this.requiredFlashVersion?true:false}catch(o){f=false}if(typeof this.alter!="undefined"&&!f)switch(this.alter.type){case "img":f=c("img",[["src",this.alter.src],["alt",this.alter.alt],
["border","0"]],[]);a=b(this.alter.href,this.alter.target);a.appendChild(f);targetContainer.appendChild(a);break;case "text":a=b(this.alter.href,this.alter.target);f=c("table",[["border",0],["cellPadding",0],["cellSpacing","0"]],[["width",this.width+"px"],["height",this.height+"px"]]);g=containerOrigin.createElement("tbody");i=containerOrigin.createElement("tr");j=c("td",[["align","center"],["valign","middle"]],[]);j.appendChild(containerOrigin.createTextNode(decodeURIComponent(this.alter.string)));
i.appendChild(j);g.appendChild(i);f.appendChild(g);a.appendChild(f);targetContainer.appendChild(a);break}else{this.flashWmode=false;g=0;for(a=this.classes.length;g<a;g++){if(this.classes[g]=="wmode_opaque")this.flashWmode="opaque";if(this.classes[g]=="wmode_transparent")this.flashWmode="transparent"}a=new SWFObject(this.src,"swf"+this.id+"_"+this.zid,this.width,this.height,this.requiredFlashVersion,null);a.addVariable("clickTAG",this.href);a.addVariable("targetTAG",this.target);a.addParam("allowScriptAccess",
"always");this.flashWmode&&a.addParam("wmode",this.flashWmode);if(this.containerTag=="iframe")targetContainer.innerHTML=a.getSWFHTML();else{f=containerOrigin.createElement("div");targetContainer.appendChild(f);a.write(f)}}break;case "js":this.source&&eval(this.source);if(this.src){a=containerOrigin.createElement("script");a.type="text/javascript";a.src=this.src;targetContainer.appendChild(a)}break;case "multiple_text":f=c("div",[],[["position","relative"]]);g=function(h,e){var m=c("td",[["class",
"ad_td_base ad"+h.width+"x"+h.height+"_td"],["valign","middle"]],[["verticalAlign","middle"]]);if(typeof e.preview_title!="undefined"){var l=b(e.href,h.target);d(l,[["class","ad_anchor"]],[]);var q=c("div",[["class","preview_title"]],[["color",h.color.title],["textDecoration","underline"]]);q.innerHTML=decodeURIComponent(e.preview_title);var p=c("div",[["class","preview_text"]],[["color",h.color.text]]);p.innerHTML=decodeURIComponent(e.preview_text);h=c("div",[["class","preview_url"]],[["color",h.color.url]]);
h.innerHTML=decodeURIComponent(e.preview_url);l.appendChild(q);l.appendChild(p);l.appendChild(h);m.appendChild(l)}return m};if(this.containerTag=="iframe"||!jp.atlantis.mashiron.isStyleSheetLoaded){a=containerOrigin.createElement("link");a.rel="stylesheet";a.type="text/css";a.href=this.pathTextAdCSS;containerOrigin.getElementsByTagName("head")[0].appendChild(a);if(this.containerTag!="iframe")jp.atlantis.mashiron.isStyleSheetLoaded=true}d(f,[["class","ad_content"]],[["backgroundColor",this.color.background]]);
switch(this.boxType){case "rectangle":case "skyscraper":i=c("div",[["class","ad_title"]],[["width",this.width+"px"],["backgroundColor",this.color.border],["lineHeight","14px"]]);a=c("a",[["target","_blank"],["href",this.adlantisInfoURL]],[["color","#000"],["margin","0"],["padding","0"],["textDecoration","none"]]);a.innerHTML="Ads by <b>Adlantis</b>";i.appendChild(a);f.appendChild(i);break}i=c("table",[["class","ad_base ad"+this.width+"x"+this.height],["cellPadding","0"],["cellSpacing","0"]],[]);j=
containerOrigin.createElement("tbody");switch(this.boxType){case "rectangle":case "skyscraper":k=0;for(a=this.ads.length;k<a;k++){var n=c("tr",[],[]);n.appendChild(g(this,this.ads[k]));j.appendChild(n)}break;case "banner":n=c("tr",[],[]);k=0;for(a=this.ads.length;k<a;k++)n.appendChild(g(this,this.ads[k]));j.appendChild(n);break}i.appendChild(j);f.appendChild(i);switch(this.boxType){case "banner":g=c("span",[],[["position","absolute"],["top",this.height-15+"px"],["left",this.width-84+"px"],["padding",
"0"],["fontSize","9px"],["lineHeight","14px"]]);a=c("a",[["target","_blank"],["href",this.adlantisInfoURL]],[["color","#000"],["margin","0px"],["padding","0px"],["textDecoration","none"]]);a.innerHTML="Ads by <b>Adlantis</b>";g.appendChild(a);f.appendChild(g);break}targetContainer.appendChild(f);break}},insertElement:function(b,d){if(arguments.length==1){document.write('<span id="'+this.id+'"></span>');var c=document.getElementById(this.id),a=c.parentNode;a.insertBefore(b,c);a.removeChild(c)}else d.appendChild(b)}};
r.register("jp.atlantis.mashiron",{advertise:t,loader:s,ads:{}})})();
