(function(){var j=function(){this.initialize.apply(this,arguments)};j.prototype={initialize:function(b){for(var a in b)this[a]=b[a];this.namespaceRoot=this.getNamespaceObject(b.NAMESPACE);for(a in b)switch(a){case "NAMESPACE":case "AUTHOR":case "VERSION":case "REQUIRES":continue;default:if(typeof this.namespaceRoot[a]=="undefined")this.namespaceRoot[a]=b[a]}this.namespaceRoot.info=b.NAMESPACE+", version: "+b.VERSION+", by "+b.AUTHOR},getNamespaceObject:function(b){b=b.split(".");for(var a=window,
c=0,e=b.length;c<e;c++){if(typeof a[b[c]]=="undefined")a[b[c]]={};a=a[b[c]];if(c==e-1)return a}}};j.Class=function(){var b={_listeners:{},extend:function(a){var c=function(){this.initialize.apply(this,arguments)};for(var e in this)c.prototype[e]=this[e];for(e in a)c.prototype[e]=a[e];for(e in b)c.prototype[e]=b[e];return c},addEventListener:function(a,c){if(typeof this._listeners[a]=="undefined")this._listeners[a]=[];this._listeners[a].push(c)},addEventListenerWithScope:function(a,c,e,k){var h=[];
h.push.apply(h,arguments);a=h.shift();if(typeof this._listeners[a]=="undefined")this._listeners[a]=[];c=h.shift();if(typeof c!="function")throw new Error("\u30ea\u30b9\u30ca\u95a2\u6570\u304c\u6b63\u3057\u304f\u30bb\u30c3\u30c8\u3055\u308c\u3066\u3044\u307e\u305b\u3093");e=h.shift();k=h.shift();if(typeof this._listeners[a]=="undefined")this._listeners[a]=[];this._listeners[a].push(function(){return c.apply(e,h)})},fire:function(){var a=[];a.push.apply(a,arguments);var c=a[0];if(typeof c=="string")c=
{type:c};if(!c.target)c.target=this;if(!c.type)throw new Error("Event object missing 'type' property.");if(this._listeners[c.type]instanceof Array){c=this._listeners[c.type];for(var e=0,k=c.length;e<k;e++)c[e].apply(this,a)}},removeEventListener:function(a,c){if(this._listeners[a]instanceof Array){a=this._listeners[a];for(var e=0;e<lenl;e++)if(a[e]===c){a.splice(e,1);break}}}};return function(){for(var a in b)this[a]=b[a];typeof this.initialize=="function"&&this.initialize.apply(this,arguments)}};
var u=j.Class();u.prototype={initialize:function(b){this.src=b.src||-1;if(!this.src)throw new Error("to load script, it must be requires `src` options in arguments");this.allowLoadWithSameUrl=b.allowLoadWithSameUrl||-1}};var t={NAMESPACE:"jp.atlantis.base",VERSION:1,AUTHOR:"ATLANTIS"};t.Module=j;t.ScriptLoader=u;new j(t);j=jp.atlantis.base.Module;new j({NAMESPACE:"jp.atlantis.util",VERSION:1,AUTHOR:"ATLANTIS",packager:{isAvailable:function(b){b=b.split(".");for(var a=window,c=0,e=b.length;c<e;c++){if(typeof a[b[c]]==
"undefined")return false;a=a[b[c]]}return true}},evaluateJsonText:function(b){return typeof JSON!="undefined"&&typeof JSON.parse!="undefined"?JSON.parse(b):/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+b+")"):false},getHashedKey:function(){date=new Date;i=0;for(len=date.getSeconds();i<len;i++)Math.random();return Math.floor(Math.random()*3656158444729381).toString(36)},
setProps:function(b,a){for(var c in a)b[c]=a[c];return b},sprintf:function(b){function a(d,o,g,m,l,f,r){if(r==="%")return"%";d="";f=c[r];var v;k=o?parseInt(o):e++;f&1024||(d=h[k]===void 0?"":h[k]);f&3&&(d=f&1?parseInt(d):parseFloat(d),d=isNaN(d)?"":d);f&4&&(d=((r==="s"?d:r)||"").toString());f&32&&(d=d>=0?d:d%4294967296+4294967296);f&768&&(d=d.toString(f&256?8:16));f&64&&g==="#"&&(d=(f&256?"0":"0x")+d);f&128&&l&&(d=f&2?d.toFixed(l):d.slice(0,l));f&24576&&(v=typeof d!=="number"||d<0);f&8192&&(d=v?"":
String.fromCharCode(d));f&32768&&(g=g==="0"?"":g);d=f&4096?d.toString().toUpperCase():d.toString();if(!(f&2048||m===void 0||d.length>=m)){o=Array(m-d.length+1).join(!g?" ":g==="#"?" ":g);d=f&16&&g==="0"&&!d.indexOf("-")?"-"+o+d.slice(1):o+d}return d}var c={i:32785,d:32785,u:32801,o:33121,x:33377,X:37473,f:146,c:10240,s:132},e=1,k=0,h=arguments;return b.replace(/%(?:(\d+)\$)?(#|0)?(\d+)?(?:\.(\d+))?(l)?([%iduoxXfcs])/g,a)},bind:function(){var b=[];b.push.apply(b,arguments);var a=b.shift(),c=b.shift();
return function(){return a.apply(c,arguments)}}});var p=[{packageName:"jp.atlantis.mashiron.advertise",src:"http://a.adimg.net/javascripts/adlantis.www.js"},{packageName:"SWFObject",src:"http://a.adimg.net/javascripts/swfobject.js"}],w=/(iPhone OS|Android)/.test(navigator.userAgent)?true:false;/(Android)/.test(navigator.userAgent);w&&p.push({packageName:"jp.atlantis.yuno",src:"http://a.adimg.net/javascripts/adlantis.sp.js?1431430555"});var s=function(){var b=jp.atlantis.yuno,a=jp.atlantis.alto;new jp.atlantis.mashiron.loader;
if(w){window.SmartPhone=(new a.smartphone).detect();new b.Loader}},q=function(){var b=function(g){g=g.split(".");for(var m=window,l=0,f=g.length;l<f;l++){if(typeof m[g[l]]=="undefined")return false;m=m[g[l]]}return true};if(!window.__ld){window.__ld=true;if(p.length){for(var a=window.opera&&parseFloat(window.opera.version())<9?true:false,c=[],e=0,k=p.length;e<k;e++)b(p[e].packageName)||c.push(p[e]);var h=c.length;for(e=0;e<c.length;e++){k=c[e];var d=document.createElement("script");d.type="text/javascript";
d.charset="utf-8";d.src=k.src;if(window.ActiveXObject)d.onreadystatechange=function(){if(d.readyState=="complete"||d.readyState=="loaded"){for(var g=0,m=0,l=p.length;g<l;g++)b(p[g].packageName)&&m++;m==l&&s()}};else d.onload=function(){h--;h==0&&s.apply()};a?document.body.appendChild(d):document.documentElement.appendChild(d)}if(a){s();var o=function(){try{s()}catch(g){setTimeout(o,99)}};o()}}}};if(window.attachEvent&&!window.opera){j=false;try{for(var n=window.parent,x=window.self;n&&n!=x;){if(n.location.host!=
x.location.host){j=true;break}if(n===n.parent)break;n=n.parent}}catch(y){j=true}j?window.attachEvent("onload",function(){q(1)}):function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,50);return}q(1)}()}else if(window.opera){n=parseFloat(window.opera.version());if(n<9)window.addEventListener("load",q,false);else n<9.5?document.addEventListener("DOMContentLoaded",q,false):window.addEventListener("DOMContentLoaded",q,true)}else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
q,true);else window.onload=q()})();
